version: "3.0"
services:
    # event-planner-app:
    #     build: .
    #     ports:
    #         - "80:80"
    #     environment:
     #      - KEY: VALUE 
    event-planner-service:
        image: jmagnojunior/event-planner-service:latest
        ports:
            - "8080:8080"
        environment:
            CALLBACK_URL: http://localhost:8080/v1/auth
    